// Welcome screen and dialog strings, taken from classic TeamGrid's locales
// (src/i18n/locales/*.json) so both apps say the same. Languages outside
// this list fall back to English.

export const WELCOME_STRINGS = {
  "en": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "New spreadsheet",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Import XLSX...",
    "openTitle": "Open spreadsheet",
    "templateTitle": "New from template",
    "empty": "No spreadsheets in this category.",
    "emptyTemplates": "No template spreadsheets in this category.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Title",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Cancel",
    "create": "Create",
    "open": "Open"
  },
  "de": {
    "title": "Gemeinsame Tabellen",
    "body": "Erstelle eine neue Tabelle oder öffne eine vorhandene. Bearbeite Zellen, schreibe Formeln, organisiere deine Arbeit auf mehreren Blattregistern und sieh die Änderungen deiner Teammitglieder in Echtzeit.",
    "newDocument": "Neue Tabelle",
    "openDocument": "Tabelle öffnen",
    "newFromTemplate": "Neu aus Vorlage...",
    "importXlsx": "XLSX importieren...",
    "openTitle": "Tabelle öffnen",
    "templateTitle": "Neu aus Vorlage",
    "empty": "Keine Tabellen in dieser Kategorie.",
    "emptyTemplates": "Keine Vorlagentabellen in dieser Kategorie.",
    "newTitle": "Neue Tabelle",
    "titleLabel": "Titel",
    "titlePlaceholder": "Tabellentitel",
    "untitled": "Unbenannte Tabelle",
    "copyOf": "Kopie von {title}",
    "cancel": "Abbrechen",
    "create": "Erstellen",
    "open": "Öffnen"
  },
  "fr": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nouveau tableur",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importer XLSX...",
    "openTitle": "Ouvrir une feuille",
    "templateTitle": "Nouveau à partir d’un modèle",
    "empty": "Aucune feuille dans cette catégorie.",
    "emptyTemplates": "Aucun modèle de feuille dans cette catégorie.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titre",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annuler",
    "create": "Créer",
    "open": "Ouvrir"
  },
  "it": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nuovo foglio di calcolo",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importa XLSX...",
    "openTitle": "Apri foglio",
    "templateTitle": "Nuovo da modello",
    "empty": "Nessun foglio in questa categoria.",
    "emptyTemplates": "Nessun modello di foglio in questa categoria.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titolo",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annulla",
    "create": "Crea",
    "open": "Apri"
  },
  "es": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nueva hoja de cálculo",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importar XLSX...",
    "openTitle": "Abrir hoja",
    "templateTitle": "Nuevo desde plantilla",
    "empty": "No hay hojas en esta categoría.",
    "emptyTemplates": "No hay plantillas de hoja en esta categoría.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Título",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Cancelar",
    "create": "Crear",
    "open": "Abrir"
  },
  "nl": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nieuw spreadsheet",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "XLSX importeren...",
    "openTitle": "Spreadsheet openen",
    "templateTitle": "Nieuw van sjabloon",
    "empty": "Geen spreadsheets in deze categorie.",
    "emptyTemplates": "Geen sjabloonspreadsheets in deze categorie.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titel",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annuleren",
    "create": "Maken",
    "open": "Openen"
  },
  "nb": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nytt regneark",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importer XLSX...",
    "openTitle": "Åpne regneark",
    "templateTitle": "Ny fra mal",
    "empty": "Ingen regneark i denne kategorien.",
    "emptyTemplates": "Ingen mal-regneark i denne kategorien.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Tittel",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Avbryt",
    "create": "Opprett",
    "open": "Åpne"
  },
  "pl": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nowy arkusz",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importuj XLSX...",
    "openTitle": "Otwórz arkusz",
    "templateTitle": "Nowy z szablonu",
    "empty": "Brak arkuszy w tej kategorii.",
    "emptyTemplates": "Brak szablonów arkuszy w tej kategorii.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Tytuł",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Anuluj",
    "create": "Utwórz",
    "open": "Otwórz"
  }
} as const

export type WelcomeStrings = Record<keyof (typeof WELCOME_STRINGS)['en'], string>

export function welcomeStrings(language: string): WelcomeStrings {
  const all: Record<string, WelcomeStrings> = WELCOME_STRINGS
  return all[language] ?? all.en!
}
