// Strings of TeamGrid's own screens (welcome, file menu, dialogs), taken from
// classic TeamGrid's locales (src/i18n/locales/*.json) so both apps say the
// same. Languages outside this list fall back to English.

export const WELCOME_STRINGS = {
  "en": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "New spreadsheet",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Import XLSX...",
    "exportXlsx": "Export XLSX",
    "file": "File",
    "openTitle": "Open spreadsheet",
    "templateTitle": "New from template",
    "empty": "No spreadsheets in this category.",
    "emptyTemplates": "No template spreadsheets in this category.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Title",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Cancel",
    "create": "Create",
    "open": "Open",
    "save": "Save",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Tags",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Enter one tag per line. Use a backslash to create hierarchy, for example Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Save as",
    "close": "Close",
    "unsavedTitle": "Unsaved changes",
    "unsavedBody": "Save the changes to “{title}” before closing?",
    "dontSave": "Don't save"
  },
  "de": {
    "title": "Gemeinsame Tabellen",
    "body": "Erstelle eine neue Tabelle oder öffne eine vorhandene. Bearbeite Zellen, schreibe Formeln, organisiere deine Arbeit auf mehreren Blattregistern und sieh die Änderungen deiner Teammitglieder in Echtzeit.",
    "newDocument": "Neue Tabelle",
    "openDocument": "Tabelle öffnen",
    "newFromTemplate": "Neu aus Vorlage...",
    "importXlsx": "XLSX importieren...",
    "exportXlsx": "XLSX exportieren",
    "file": "Datei",
    "openTitle": "Tabelle öffnen",
    "templateTitle": "Neu aus Vorlage",
    "empty": "Keine Tabellen in dieser Kategorie.",
    "emptyTemplates": "Keine Vorlagentabellen in dieser Kategorie.",
    "newTitle": "Neue Tabelle",
    "titleLabel": "Titel",
    "titlePlaceholder": "Tabellentitel",
    "untitled": "Unbenannte Tabelle",
    "copyOf": "Kopie von {title}",
    "cancel": "Abbrechen",
    "create": "Erstellen",
    "open": "Öffnen",
    "save": "Speichern",
    "propertiesTitle": "Tabelleneigenschaften",
    "tagsLabel": "Tags",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Gib pro Zeile einen Tag ein. Verwende einen Backslash für Hierarchien, zum Beispiel Work\\Planning.",
    "useAsTemplate": "Diese Tabelle als Vorlage verwenden",
    "saveAsTitle": "Speichern unter",
    "close": "Schließen",
    "unsavedTitle": "Ungespeicherte Änderungen",
    "unsavedBody": "Änderungen an „{title}“ vor dem Schließen speichern?",
    "dontSave": "Nicht speichern"
  },
  "fr": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nouveau tableur",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importer XLSX...",
    "exportXlsx": "Exporter XLSX",
    "file": "Fichier",
    "openTitle": "Ouvrir une feuille",
    "templateTitle": "Nouveau à partir d’un modèle",
    "empty": "Aucune feuille dans cette catégorie.",
    "emptyTemplates": "Aucun modèle de feuille dans cette catégorie.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titre",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annuler",
    "create": "Créer",
    "open": "Ouvrir",
    "save": "Enregistrer",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Étiquettes",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Saisissez une étiquette par ligne. Utilisez une barre oblique inverse pour créer une hiérarchie, par exemple Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Enregistrer sous",
    "close": "Fermer",
    "unsavedTitle": "Modifications non enregistrées",
    "unsavedBody": "Enregistrer les modifications de « {title} » avant de fermer ?",
    "dontSave": "Ne pas enregistrer"
  },
  "it": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nuovo foglio di calcolo",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importa XLSX...",
    "exportXlsx": "Esporta XLSX",
    "file": "File",
    "openTitle": "Apri foglio",
    "templateTitle": "Nuovo da modello",
    "empty": "Nessun foglio in questa categoria.",
    "emptyTemplates": "Nessun modello di foglio in questa categoria.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titolo",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annulla",
    "create": "Crea",
    "open": "Apri",
    "save": "Salva",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Tag",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Inserisci un tag per riga. Usa una barra rovesciata per creare una gerarchia, ad esempio Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Salva con nome",
    "close": "Chiudi",
    "unsavedTitle": "Modifiche non salvate",
    "unsavedBody": "Salvare le modifiche a «{title}» prima di chiudere?",
    "dontSave": "Non salvare"
  },
  "es": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nueva hoja de cálculo",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importar XLSX...",
    "exportXlsx": "Exportar XLSX",
    "file": "Archivo",
    "openTitle": "Abrir hoja",
    "templateTitle": "Nuevo desde plantilla",
    "empty": "No hay hojas en esta categoría.",
    "emptyTemplates": "No hay plantillas de hoja en esta categoría.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Título",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Cancelar",
    "create": "Crear",
    "open": "Abrir",
    "save": "Guardar",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Etiquetas",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Introduce una etiqueta por línea. Usa una barra invertida para crear una jerarquía, por ejemplo Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Guardar como",
    "close": "Cerrar",
    "unsavedTitle": "Cambios sin guardar",
    "unsavedBody": "¿Guardar los cambios de «{title}» antes de cerrar?",
    "dontSave": "No guardar"
  },
  "nl": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nieuw spreadsheet",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "XLSX importeren...",
    "exportXlsx": "XLSX exporteren",
    "file": "Bestand",
    "openTitle": "Spreadsheet openen",
    "templateTitle": "Nieuw van sjabloon",
    "empty": "Geen spreadsheets in deze categorie.",
    "emptyTemplates": "Geen sjabloonspreadsheets in deze categorie.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Titel",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Annuleren",
    "create": "Maken",
    "open": "Openen",
    "save": "Opslaan",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Tags",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Voer één tag per regel in. Gebruik een backslash om een hiërarchie te maken, bijvoorbeeld Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Opslaan als",
    "close": "Sluiten",
    "unsavedTitle": "Niet-opgeslagen wijzigingen",
    "unsavedBody": "Wijzigingen in ‘{title}’ opslaan voordat je sluit?",
    "dontSave": "Niet opslaan"
  },
  "nb": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nytt regneark",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importer XLSX...",
    "exportXlsx": "Eksporter XLSX",
    "file": "Fil",
    "openTitle": "Åpne regneark",
    "templateTitle": "Ny fra mal",
    "empty": "Ingen regneark i denne kategorien.",
    "emptyTemplates": "Ingen mal-regneark i denne kategorien.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Tittel",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Avbryt",
    "create": "Opprett",
    "open": "Åpne",
    "save": "Lagre",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Tagger",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Skriv inn én tagg per linje. Bruk bakoverstrek for å lage hierarki, for eksempel Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Lagre som",
    "close": "Lukk",
    "unsavedTitle": "Ulagrede endringer",
    "unsavedBody": "Lagre endringene i «{title}» før du lukker?",
    "dontSave": "Ikke lagre"
  },
  "pl": {
    "title": "Collaborative spreadsheets",
    "body": "Create a new spreadsheet or open an existing one. Edit cells, write formulas, organize your work across multiple sheet tabs, and see your teammates' changes in real time.",
    "newDocument": "Nowy arkusz",
    "openDocument": "Open spreadsheet",
    "newFromTemplate": "New from template...",
    "importXlsx": "Importuj XLSX...",
    "exportXlsx": "Eksportuj XLSX",
    "file": "Plik",
    "openTitle": "Otwórz arkusz",
    "templateTitle": "Nowy z szablonu",
    "empty": "Brak arkuszy w tej kategorii.",
    "emptyTemplates": "Brak szablonów arkuszy w tej kategorii.",
    "newTitle": "New spreadsheet",
    "titleLabel": "Tytuł",
    "titlePlaceholder": "Spreadsheet title",
    "untitled": "Untitled spreadsheet",
    "copyOf": "Copy of {title}",
    "cancel": "Anuluj",
    "create": "Utwórz",
    "open": "Otwórz",
    "save": "Zapisz",
    "propertiesTitle": "Spreadsheet properties",
    "tagsLabel": "Tagi",
    "tagsPlaceholder": "Work\\Planning\nCustomer\\ABC",
    "tagsHint": "Wpisz jeden tag w wierszu. Użyj ukośnika wstecznego, aby utworzyć hierarchię, na przykład Work\\Planning.",
    "useAsTemplate": "Use this spreadsheet as a template",
    "saveAsTitle": "Zapisz jako",
    "close": "Zamknij",
    "unsavedTitle": "Niezapisane zmiany",
    "unsavedBody": "Zapisać zmiany w „{title}” przed zamknięciem?",
    "dontSave": "Nie zapisuj"
  }
} as const

export type WelcomeStrings = Record<keyof (typeof WELCOME_STRINGS)['en'], string>

export function welcomeStrings(language: string): WelcomeStrings {
  const all: Record<string, WelcomeStrings> = WELCOME_STRINGS
  return all[language] ?? all.en!
}
